#' Beta diversity function for FCM data
#'
#' This function performs beta diversity analysis on FCM data. 
#' The output can be fed into the plot.beta.fcm() function for visualization.
#' @param x flowbasis object generated by flowBasis()
#' @param d Rounding factor for density values. Defaults to 4.
#' @param n Number of samples to pool? Defaults to 1. For n>1 samples will be pooled and averaged. 
#' Make sure samples are ordered per factor level.
#' @param dist Distance metric to use in the vegdist() function. Defaults to bray.
#' @param k Number of dimensions to project your samples into. Defaults to 2.
#' @param iter Number of iterations for NMDS analysis. Defaults to 100.
#' @param ord.type Choose between NMDS or PCoA analysis.
#' @keywords betadiversity, fcm
#' @export
#' @examples
#' beta.div.fcm()

beta.div.fcm <- function(x, d=3, n=1, dist="bray", k=2, iter=100,
                         ord.type=c("NMDS", "PCoA"))
{
  x <- x@basis/apply(x@basis, 1, max)
  input <- matrix(nrow=nrow(x)/n, ncol=ncol(x))
  j <- 1
  if (n > 1)
  {
    for (i in seq(1, nrow(x), n))
    {
      if (n > 1) 
        input[j, ] <- round(colMeans(x[(i:(i + (n - 1))), ]), d)
      j = j + 1
    }
    rownames(input) <- rownames(x)[seq(1, nrow(x), n)]
    input.dist <- vegan::vegdist(input, method=dist)
    if (ord.type == "NMDS") 
      mds.fbasis <- vegan::metaMDS(input.dist, autotransform=FALSE, k,
                                   trymax=iter) 
    else mds.fbasis <- stats::cmdscale(input.dist, k=2, eig=TRUE, add=TRUE)
  } else
  {
    input.dist <- vegan::vegdist(x, method=dist)
    if (ord.type == "NMDS") 
      mds.fbasis <- vegan::metaMDS(input.dist, autotransform = FALSE, k,
                                   trymax=iter) 
    else mds.fbasis <- stats::cmdscale(input.dist, k = 2, eig=TRUE, add=TRUE)
  }
  return(mds.fbasis)
}
