#' Diversity function for 16S amplicon data
#'
#' This function calculates Hill diversity metrics from 16S amplicon data (in phyloseq format).
#' D0 (richness) is calculated with three methods: 1) Observed richness, 2) Chao1 estimator
#' 3) breakaway method (Willis and Bunge 2016). D1 (exponential of Shannon entropy)
#' and D2 (inverse Simpson index) are respectively Hill order 1 and 2
#' Errors for D1 and D2 are calculated by bootstrapping.
#' @param x phyloseq object generated by the phyloseq package
#' @param R Number of bootstraps to conduct. Defaults to 999
#' @keywords diversity, fcm, alpha
#' @examples  
#' 
#' ## Short example
#' 
#' # Load precomputed fingerprint object
#' data(CoolingTower)
#' 
#' # Calculate diversity values
#' Diversity(CoolingTower, plot=TRUE)
#' 
#' ## Full data processing example
#' 
#' # Load raw data (imported using flowCore)
#' data(flowData)
#' # Asinh transform and select parameters of interest 
#' (cells were stained with Sybr Green I).
#' flowData_transformed <- transform(flowData,`FL1-H`=asinh(`FL1-H`),
#' `SSC-H`=asinh(`SSC-H`), 
#' `FL3-H`=asinh(`FL3-H`), 
#' `FSC-H`=asinh(`FSC-H`))
#' param=c("FL1-H", "FL3-H","SSC-H","FSC-H")
#' flowData_transformed = flowData_transformed[,param]
#' 
#' # Create a PolygonGate for denoising the dataset
#' # Define coordinates for gate in sqrcut1 in format: c(x,x,x,x,y,y,y,y)
#' sqrcut1 <- matrix(c(8.75,8.75,14,14,3,7.5,14,3),ncol=2, nrow=4)
#' colnames(sqrcut1) <- c("FL1-H","FL3-H")
#' polyGate1 <- polygonGate(.gate=sqrcut1, filterId = "Total Cells")
#' 
#' # Gating quality check
#' xyplot(`FL3-H` ~ `FL1-H`, data=flowData_transformed[1], filter=polyGate1,
#' scales=list(y=list(limits=c(0,14)),
#'  x=list(limits=c(6,16))),
#'  axis = axis.default, nbin=125, 
#'  par.strip.text=list(col="white", font=2, cex=2), smooth=FALSE)
#'  
#'  # Isolate only the cellular information based on the polyGate1
#'  flowData_transformed <- Subset(flowData_transformed, polyGate1)
#'  
#'  # Normalize parameter values to [0,1] interval based on max. value across parameters
#'  summary <- fsApply(x=flowData_transformed,FUN=function(x) apply(x,2,max),use.exprs=TRUE)
#'  max = max(summary[,1])
#'  mytrans <- function(x) x/max
#'  flowData_transformed <- transform(flowData_transformed,`FL1-H`=mytrans(`FL1-H`),
#'  `FL3-H`=mytrans(`FL3-H`), 
#'  `SSC-H`=mytrans(`SSC-H`),
#'  `FSC-H`=mytrans(`FSC-H`))
#'  
#'  # Calculate fingerprint
#'  fbasis <- flowBasis(flowData_transformed, param, nbin=128, 
#'  bw=0.01,normalize=function(x) x)
#'  
#'  # Calculate diversity
#'  Diversity(fbasis, plot=TRUE)
#' 
#' @export

Diversity_16S <- function(x, R=999){
  cat("\t**WARNING** this functions assumes that rows are samples and columns
      \tare taxa in your phyloseq object, please verify.\n")
  
  # Matrix for storing data
  DIV <- matrix(nrow = phyloseq::nsamples(x), ncol = 10)
  row.names(DIV) <- phyloseq::sample_names(x)
  
  # Diversity functions
  D0.boot <- function(x) sum(x!=0)
  D2.boot <- function(x) 1/sum((x)^2)
  D1.boot <- function(x) exp(-sum(x*log(x)))
  
  # Start resampling
  for(i in 1:phyloseq::nsamples(x)){
    temp.D0 <- c(); temp.D1 <-c(); temp.D2 <- c()
    temp.phy <- phyloseq::prune_samples(x=x, samples=phyloseq::sample_names(x)[i])
    cat(paste0(date(),"\tStarting sample ",phyloseq::sample_names(x)[i],"\n"))
    for(j in 1:R){
      temp <- phyloseq::rarefy_even_depth(temp.phy, verbose=FALSE, replace=TRUE)
      # Calculate frequencies
      temp <- data.frame(phyloseq::transform_sample_counts(temp, fun= function(x) x/sum(x))@otu_table)
      # Calculate Diversities
      temp.D0 <- c(temp.D0, D0.boot(temp))
      temp.D1 <- c(temp.D1, D1.boot(temp))  
      temp.D2 <- c(temp.D2, D2.boot(temp))
      # Store diversities at the end of resampling run  
      if(j==R){
        DIV[i,1] <- mean(temp.D0)
        DIV[i,2] <- stats::sd(temp.D0)
        DIV[i,7] <- mean(temp.D1)
        DIV[i,8] <- stats::sd(temp.D1)
        DIV[i,9] <- mean(temp.D2)
        DIV[i,10] <- stats::sd(temp.D2)
        remove(temp.D0, temp.D1, temp.D2)
        cat(paste0(date(),"\tDone with sample ", phyloseq::sample_names(x)[i],"\n"))
      }
    }
    # Perform breakaway for richness estimation
    temp <- t(matrix(temp.phy@otu_table)); temp <- temp[temp!=0]
    temp <- data.frame(table(temp))
    rich <- breakaway::breakaway(temp,print=FALSE,plot=FALSE,answers=TRUE)
    DIV[i,3] <- rich$est
    DIV[i,4] <- rich$seest
    rich.chao <- breakaway::chao1(temp, print=FALSE, answers=TRUE)
    DIV[i,5] <- rich.chao$est
    DIV[i,6] <- rich.chao$seest
  }
  colnames(DIV) = c("D0","se.D0","D0.bre","se.D0.bre","D0.chao","se.D0.chao","D1","sd.D1","D2","sd.D2")
  cat(date(),"\t Done with all", phyloseq::nsamples(x),"samples\n")
  return(DIV)
}