#' Structural organisation (So) for FCM data based on Koch et al. 2014
#'
#' This function calculates Structural organisation from FCM data according to Koch et al. 2014.
#' @param x flowbasis object generated by flowBasis()
#' @param d Rounding factor for density values. Defaults to 4.
#' @param plot Make plot of diversity values? Defaults to FALSE.
#' @param n Number of replicates. Defaults to 1.
#' @keywords So, fcm, structural organization
#' @export
#' @examples
#' So()

So <- function(x,d=3,n=1,plot=FALSE){
  x<- x@basis/apply(x@basis, 1, max)
  So = apply(x,1,FUN=function(x){
    x = round(x,d);x<-x[x!=0];sum(abs(x-mean(x)))/(length(x))
  })
  if(n>1){
    results = matrix(nrow=length(x[,1])/3, ncol=2)
    results[,1]=trip(So,n)[,1]
    results[,2]=trip(So,n)[,2]
    results=data.frame(results)
    colnames(results)=c("Organisation","sdev")
    rownames(results) = trip_col(attr(x,"dimnames")[[1]],n)
  }
  else{
    results <- So
    results = data.frame(results)
    colnames(results)=c("Organisation")
    rownames(results)=attr(x,"dimnames")[[1]]
  }
  if (plot==TRUE) {
    graphics::plot(Structural.organization.fbasis$Organisation,pch=21,
         bg=adjustcolor("blue",0.7),col=adjustcolor("blue",0.7),cex=1.5,
         las=1,ylab="SO",xlab="Samples")
  }
  return(results)
}